# Generated by Django 3.1.7 on 2021-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gaji',
            field=models.IntegerField(default=0),
        ),
    ]
