# Generated by Django 3.1.7 on 2021-04-21 02:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0002_presensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presensi',
            name='jam_masuk',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='presensi',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
