# Generated by Django 3.1.7 on 2021-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210423_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaktivitas',
            name='notes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
