# Generated by Django 3.1.7 on 2021-04-24 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0003_logaktivitas_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presensi', to='log.logaktivitas'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presensi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to=settings.AUTH_USER_MODEL),
        ),
    ]
