# Generated by Django 3.1.7 on 2021-04-21 03:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0003_auto_20210421_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('jam_masuk', models.TimeField(default=django.utils.timezone.now)),
                ('jam_keluar', models.TimeField(default=django.utils.timezone.now)),
                ('keterangan', models.CharField(max_length=50)),
                ('aktivitas', models.CharField(max_length=250)),
                ('link_deliverable', models.CharField(max_length=250)),
                ('status_deliverable', models.CharField(max_length=50)),
                ('tipe_log', models.CharField(max_length=35)),
                ('status_log', models.CharField(max_length=35)),
                ('komentar', models.CharField(max_length=250)),
                ('alasan_lembur', models.CharField(max_length=250)),
                ('manajer_penyetuju', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manajer_penyetuju', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
