# Generated by Django 3.1.7 on 2021-04-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20210424_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='log',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presensi', to='log.logaktivitas'),
        ),
    ]
