# Generated by Django 3.1.7 on 2021-04-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_logaktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='log.logaktivitas'),
        ),
    ]
