# Generated by Django 3.1.7 on 2021-04-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_presensi_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaktivitas',
            name='manajer_penyetuju',
        ),
    ]
