# Generated by Django 3.1.7 on 2021-04-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_remove_logaktivitas_manajer_penyetuju'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='presensi',
            name='log',
        ),
    ]
