# Generated by Django 3.1.7 on 2021-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_remove_logaktivitas_manajer_penyetuju'),
        ('log', '0008_auto_20210421_2223'),
    ]

    operations = [
    ]
