# Generated by Django 3.1.7 on 2021-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20210421_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaktivitas',
            name='tipe_log',
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='is_lembur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='alasan_lembur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
