# Generated by Django 3.1.7 on 2021-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_logaktivitas_user'),
        ('log', '0007_auto_20210421_1708'),
    ]

    operations = [
    ]
