# Generated by Django 3.1.7 on 2021-04-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0011_merge_20210423_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaktivitas',
            name='manajer_penyetuju',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manajer_penyetuju', to=settings.AUTH_USER_MODEL),
        ),
    ]
