# Generated by Django 3.1.7 on 2021-04-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borang', '0001_initial'),
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaketJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paket_jawaban', to='assign.assignment')),
                ('paket_pertanyaan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borang.paketpertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
                ('tipe', models.IntegerField()),
                ('pertanyaan', models.CharField(max_length=255)),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_jawaban', to='jawaban.aspekjawaban')),
            ],
        ),
        migrations.AddField(
            model_name='aspekjawaban',
            name='paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_aspek', to='jawaban.paketjawaban'),
        ),
    ]
