# Generated by Django 3.1.7 on 2021-04-11 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borang', '0002_auto_20210409_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('list_paket_pertanyaan', models.ManyToManyField(related_name='list_assignment', to='borang.PaketPertanyaan')),
                ('user_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dinilai', to=settings.AUTH_USER_MODEL)),
                ('user_penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_penilai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaketJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paket_jawaban', to='jawaban.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
                ('tipe', models.IntegerField()),
                ('aspek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_jawaban', to='jawaban.aspekjawaban')),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borang.pertanyaan')),
            ],
        ),
        migrations.AddField(
            model_name='aspekjawaban',
            name='paket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_aspek', to='jawaban.paketjawaban'),
        ),
    ]
