# Generated by Django 3.1.7 on 2021-04-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
        ('jawaban', '0002_auto_20210412_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketjawaban',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paket_jawaban', to='assign.assignment'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
