# Generated by Django 3.1.7 on 2021-04-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jawaban', '0003_auto_20210412_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawaban',
            name='pertanyaan',
            field=models.CharField(max_length=255),
        ),
    ]
