# Generated by Django 3.1.7 on 2021-04-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borang', '0002_auto_20210409_0006'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('list_paket_pertanyaan', models.ManyToManyField(related_name='list_assignment', to='borang.PaketPertanyaan')),
                ('user_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dinilai', to=settings.AUTH_USER_MODEL)),
                ('user_penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_penilai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_penilai', 'user_dinilai', 'periode')},
            },
        ),
    ]
