# Generated by Django 3.1.7 on 2021-04-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspekPertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriPertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('tipe', models.IntegerField()),
                ('aspek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borang.aspekpertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='PaketPertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borang.kategoripertanyaan')),
            ],
        ),
        migrations.AddField(
            model_name='aspekpertanyaan',
            name='paket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borang.paketpertanyaan'),
        ),
    ]
