# Generated by Django 3.1.7 on 2021-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspekpertanyaan',
            name='bobot',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
