# Generated by Django 3.1.7 on 2021-04-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borang', '0002_auto_20210421_1003'),
        ('borang', '0002_auto_20210409_0006'),
    ]

    operations = [
    ]
