# Generated by Django 3.1.7 on 2021-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borang', '0003_merge_20210421_1640'),
        ('borang', '0003_merge_20210421_1733'),
    ]

    operations = [
    ]
